// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: api/supervisor.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Supervisor_Health_FullMethodName      = "/supervisor.Supervisor/Health"
	Supervisor_AcquirePort_FullMethodName = "/supervisor.Supervisor/AcquirePort"
	Supervisor_ReleasePort_FullMethodName = "/supervisor.Supervisor/ReleasePort"
	Supervisor_SpawnAgent_FullMethodName  = "/supervisor.Supervisor/SpawnAgent"
	Supervisor_KillAgent_FullMethodName   = "/supervisor.Supervisor/KillAgent"
)

// SupervisorClient is the client API for Supervisor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupervisorClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	AcquirePort(ctx context.Context, in *AcquirePortRequest, opts ...grpc.CallOption) (*AcquirePortResponse, error)
	ReleasePort(ctx context.Context, in *ReleasePortRequest, opts ...grpc.CallOption) (*ReleasePortResponse, error)
	SpawnAgent(ctx context.Context, in *SpawnAgentRequest, opts ...grpc.CallOption) (*SpawnAgentResponse, error)
	KillAgent(ctx context.Context, in *KillAgentRequest, opts ...grpc.CallOption) (*KillAgentResponse, error)
}

type supervisorClient struct {
	cc grpc.ClientConnInterface
}

func NewSupervisorClient(cc grpc.ClientConnInterface) SupervisorClient {
	return &supervisorClient{cc}
}

func (c *supervisorClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Supervisor_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) AcquirePort(ctx context.Context, in *AcquirePortRequest, opts ...grpc.CallOption) (*AcquirePortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquirePortResponse)
	err := c.cc.Invoke(ctx, Supervisor_AcquirePort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) ReleasePort(ctx context.Context, in *ReleasePortRequest, opts ...grpc.CallOption) (*ReleasePortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleasePortResponse)
	err := c.cc.Invoke(ctx, Supervisor_ReleasePort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) SpawnAgent(ctx context.Context, in *SpawnAgentRequest, opts ...grpc.CallOption) (*SpawnAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnAgentResponse)
	err := c.cc.Invoke(ctx, Supervisor_SpawnAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) KillAgent(ctx context.Context, in *KillAgentRequest, opts ...grpc.CallOption) (*KillAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillAgentResponse)
	err := c.cc.Invoke(ctx, Supervisor_KillAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupervisorServer is the server API for Supervisor service.
// All implementations must embed UnimplementedSupervisorServer
// for forward compatibility.
type SupervisorServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	AcquirePort(context.Context, *AcquirePortRequest) (*AcquirePortResponse, error)
	ReleasePort(context.Context, *ReleasePortRequest) (*ReleasePortResponse, error)
	SpawnAgent(context.Context, *SpawnAgentRequest) (*SpawnAgentResponse, error)
	KillAgent(context.Context, *KillAgentRequest) (*KillAgentResponse, error)
	mustEmbedUnimplementedSupervisorServer()
}

// UnimplementedSupervisorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSupervisorServer struct{}

func (UnimplementedSupervisorServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSupervisorServer) AcquirePort(context.Context, *AcquirePortRequest) (*AcquirePortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquirePort not implemented")
}
func (UnimplementedSupervisorServer) ReleasePort(context.Context, *ReleasePortRequest) (*ReleasePortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleasePort not implemented")
}
func (UnimplementedSupervisorServer) SpawnAgent(context.Context, *SpawnAgentRequest) (*SpawnAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpawnAgent not implemented")
}
func (UnimplementedSupervisorServer) KillAgent(context.Context, *KillAgentRequest) (*KillAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillAgent not implemented")
}
func (UnimplementedSupervisorServer) mustEmbedUnimplementedSupervisorServer() {}
func (UnimplementedSupervisorServer) testEmbeddedByValue()                    {}

// UnsafeSupervisorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupervisorServer will
// result in compilation errors.
type UnsafeSupervisorServer interface {
	mustEmbedUnimplementedSupervisorServer()
}

func RegisterSupervisorServer(s grpc.ServiceRegistrar, srv SupervisorServer) {
	// If the following call pancis, it indicates UnimplementedSupervisorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Supervisor_ServiceDesc, srv)
}

func _Supervisor_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_AcquirePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquirePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).AcquirePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_AcquirePort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).AcquirePort(ctx, req.(*AcquirePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_ReleasePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleasePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).ReleasePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_ReleasePort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).ReleasePort(ctx, req.(*ReleasePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_SpawnAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).SpawnAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_SpawnAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).SpawnAgent(ctx, req.(*SpawnAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_KillAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).KillAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_KillAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).KillAgent(ctx, req.(*KillAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Supervisor_ServiceDesc is the grpc.ServiceDesc for Supervisor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Supervisor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "supervisor.Supervisor",
	HandlerType: (*SupervisorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Supervisor_Health_Handler,
		},
		{
			MethodName: "AcquirePort",
			Handler:    _Supervisor_AcquirePort_Handler,
		},
		{
			MethodName: "ReleasePort",
			Handler:    _Supervisor_ReleasePort_Handler,
		},
		{
			MethodName: "SpawnAgent",
			Handler:    _Supervisor_SpawnAgent_Handler,
		},
		{
			MethodName: "KillAgent",
			Handler:    _Supervisor_KillAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/supervisor.proto",
}
