# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: supervisor.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'supervisor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10supervisor.proto\x12\nsupervisor\"\x0f\n\rHealthRequest\"\x1c\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"#\n\x12\x41\x63quirePortRequest\x12\r\n\x05owner\x18\x01 \x01(\t\"#\n\x13\x41\x63quirePortResponse\x12\x0c\n\x04port\x18\x01 \x01(\x05\"\"\n\x12ReleasePortRequest\x12\x0c\n\x04port\x18\x01 \x01(\x05\"!\n\x13ReleasePortResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\xc5\x01\n\x11SpawnAgentRequest\x12\x13\n\x0bposition_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x15\n\rworktree_path\x18\x03 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x04 \x03(\t\x12\x33\n\x03\x65nv\x18\x05 \x03(\x0b\x32&.supervisor.SpawnAgentRequest.EnvEntry\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\x12SpawnAgentResponse\x12\x0b\n\x03pid\x18\x01 \x01(\x05\"\'\n\x10KillAgentRequest\x12\x13\n\x0bposition_id\x18\x01 \x01(\t\"\x1f\n\x11KillAgentResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x84\x03\n\nSupervisor\x12?\n\x06Health\x12\x19.supervisor.HealthRequest\x1a\x1a.supervisor.HealthResponse\x12N\n\x0b\x41\x63quirePort\x12\x1e.supervisor.AcquirePortRequest\x1a\x1f.supervisor.AcquirePortResponse\x12N\n\x0bReleasePort\x12\x1e.supervisor.ReleasePortRequest\x1a\x1f.supervisor.ReleasePortResponse\x12K\n\nSpawnAgent\x12\x1d.supervisor.SpawnAgentRequest\x1a\x1e.supervisor.SpawnAgentResponse\x12H\n\tKillAgent\x12\x1c.supervisor.KillAgentRequest\x1a\x1d.supervisor.KillAgentResponseB\x17Z\x15studio/supervisor/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'supervisor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025studio/supervisor/api'
  _globals['_SPAWNAGENTREQUEST_ENVENTRY']._loaded_options = None
  _globals['_SPAWNAGENTREQUEST_ENVENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHREQUEST']._serialized_start=32
  _globals['_HEALTHREQUEST']._serialized_end=47
  _globals['_HEALTHRESPONSE']._serialized_start=49
  _globals['_HEALTHRESPONSE']._serialized_end=77
  _globals['_ACQUIREPORTREQUEST']._serialized_start=79
  _globals['_ACQUIREPORTREQUEST']._serialized_end=114
  _globals['_ACQUIREPORTRESPONSE']._serialized_start=116
  _globals['_ACQUIREPORTRESPONSE']._serialized_end=151
  _globals['_RELEASEPORTREQUEST']._serialized_start=153
  _globals['_RELEASEPORTREQUEST']._serialized_end=187
  _globals['_RELEASEPORTRESPONSE']._serialized_start=189
  _globals['_RELEASEPORTRESPONSE']._serialized_end=222
  _globals['_SPAWNAGENTREQUEST']._serialized_start=225
  _globals['_SPAWNAGENTREQUEST']._serialized_end=422
  _globals['_SPAWNAGENTREQUEST_ENVENTRY']._serialized_start=380
  _globals['_SPAWNAGENTREQUEST_ENVENTRY']._serialized_end=422
  _globals['_SPAWNAGENTRESPONSE']._serialized_start=424
  _globals['_SPAWNAGENTRESPONSE']._serialized_end=457
  _globals['_KILLAGENTREQUEST']._serialized_start=459
  _globals['_KILLAGENTREQUEST']._serialized_end=498
  _globals['_KILLAGENTRESPONSE']._serialized_start=500
  _globals['_KILLAGENTRESPONSE']._serialized_end=531
  _globals['_SUPERVISOR']._serialized_start=534
  _globals['_SUPERVISOR']._serialized_end=922
# @@protoc_insertion_point(module_scope)
