# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import supervisor_pb2 as supervisor__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in supervisor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SupervisorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/supervisor.Supervisor/Health',
                request_serializer=supervisor__pb2.HealthRequest.SerializeToString,
                response_deserializer=supervisor__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.AcquirePort = channel.unary_unary(
                '/supervisor.Supervisor/AcquirePort',
                request_serializer=supervisor__pb2.AcquirePortRequest.SerializeToString,
                response_deserializer=supervisor__pb2.AcquirePortResponse.FromString,
                _registered_method=True)
        self.ReleasePort = channel.unary_unary(
                '/supervisor.Supervisor/ReleasePort',
                request_serializer=supervisor__pb2.ReleasePortRequest.SerializeToString,
                response_deserializer=supervisor__pb2.ReleasePortResponse.FromString,
                _registered_method=True)
        self.SpawnAgent = channel.unary_unary(
                '/supervisor.Supervisor/SpawnAgent',
                request_serializer=supervisor__pb2.SpawnAgentRequest.SerializeToString,
                response_deserializer=supervisor__pb2.SpawnAgentResponse.FromString,
                _registered_method=True)
        self.KillAgent = channel.unary_unary(
                '/supervisor.Supervisor/KillAgent',
                request_serializer=supervisor__pb2.KillAgentRequest.SerializeToString,
                response_deserializer=supervisor__pb2.KillAgentResponse.FromString,
                _registered_method=True)


class SupervisorServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquirePort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleasePort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpawnAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KillAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SupervisorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=supervisor__pb2.HealthRequest.FromString,
                    response_serializer=supervisor__pb2.HealthResponse.SerializeToString,
            ),
            'AcquirePort': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquirePort,
                    request_deserializer=supervisor__pb2.AcquirePortRequest.FromString,
                    response_serializer=supervisor__pb2.AcquirePortResponse.SerializeToString,
            ),
            'ReleasePort': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleasePort,
                    request_deserializer=supervisor__pb2.ReleasePortRequest.FromString,
                    response_serializer=supervisor__pb2.ReleasePortResponse.SerializeToString,
            ),
            'SpawnAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnAgent,
                    request_deserializer=supervisor__pb2.SpawnAgentRequest.FromString,
                    response_serializer=supervisor__pb2.SpawnAgentResponse.SerializeToString,
            ),
            'KillAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.KillAgent,
                    request_deserializer=supervisor__pb2.KillAgentRequest.FromString,
                    response_serializer=supervisor__pb2.KillAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'supervisor.Supervisor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('supervisor.Supervisor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Supervisor:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supervisor.Supervisor/Health',
            supervisor__pb2.HealthRequest.SerializeToString,
            supervisor__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquirePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supervisor.Supervisor/AcquirePort',
            supervisor__pb2.AcquirePortRequest.SerializeToString,
            supervisor__pb2.AcquirePortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleasePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supervisor.Supervisor/ReleasePort',
            supervisor__pb2.ReleasePortRequest.SerializeToString,
            supervisor__pb2.ReleasePortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpawnAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supervisor.Supervisor/SpawnAgent',
            supervisor__pb2.SpawnAgentRequest.SerializeToString,
            supervisor__pb2.SpawnAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KillAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/supervisor.Supervisor/KillAgent',
            supervisor__pb2.KillAgentRequest.SerializeToString,
            supervisor__pb2.KillAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
